name: Release

on:
  workflow_dispatch:
    inputs:
      nextSnapshotVersion:
        description: 'Next SNAPSHOT Version (ie, 1.0.1-SNAPSHOT)'
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Log Inputs
        run: |
          echo "Next SNAPSHOT Version: ${{ github.event.inputs.nextSnapshotVersion }}"

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.BUILD_GUY_PAT }}

      # Setup JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
          cache: maven

      # Run Tests with Sonar
      - name: Build and analyze
        run: |
          mvn -B verify sonar:sonar \
            -Dsonar.projectKey=JavaMonkey-io_todo-backend
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}